use rocket_db_pools::sqlx::{ self, sqlite::SqliteRow, SqliteConnection };
use rocket::serde::{ json::from_str, Deserialize, Serialize };
use crate::utils::functions::get_from_row;

#[derive(Deserialize, Serialize, Clone)]
#[serde(crate = "rocket::serde")]
pub enum IngredientUnit {
  Liter,
  Milliliter,
  Gram,
  Kilogram,
  Celsius,
  Pound,
  Ounce,
  Teaspoon,
  Tablespoon,
  FluidOunce,
  Cup,
  Pint,
  Quart,
  Gallon,
  Fahrenheit,
}

#[derive(Serialize)]
#[serde(crate = "rocket::serde", rename_all = "camelCase")]
pub struct SerializedRecipe {
  /// Recipe UUID.
  pub uuid: String,
  /// User UUID of the author of the recipe.
  pub user_uuid: String,
  /// Unix timestamp of when the recipe was created, in seconds.
  pub created_at: u32,
  /// Unix timestamp of when the recipe was last updated, in seconds.
  pub last_updated: u32,
  /// Name of the recipe.
  pub name: String,
  /// Ingredients of the recipe.
  ///
  /// `(name, amount, unit)`
  pub ingredients: Vec<(String, f32, IngredientUnit)>,
  /// Instructions of the recipe.
  pub instructions: Option<String>,
  /// User-created category of the recipe.
  pub category: Option<String>,
  /// JSON blob of the recipe's image.
  pub image: Option<String>,
  /// Number of likes the recipe has.
  pub likes: u32,
  /// Whether the recipe was generated by an AI.
  pub is_ai_generated: bool,
}

pub struct Recipe {
  /// Recipe UUID.
  pub uuid: String,
  /// User UUID of the author of the recipe.
  pub user_uuid: String,
  /// Unix timestamp of when the recipe was created, in seconds.
  pub created_at: u32,
  /// Unix timestamp of when the recipe was last updated, in seconds.
  pub last_updated: u32,
  /// Name of the recipe.
  pub name: String,
  /// Ingredients of the recipe.
  ///
  /// `(name, amount, unit)`
  pub ingredients: Vec<(String, f32, IngredientUnit)>,
  /// Instructions of the recipe.
  pub instructions: Option<String>,
  /// User-created category of the recipe.
  pub category: Option<String>,
  /// JSON blob of the recipe's image.
  pub image: Option<String>,
  /// Whether the recipe was generated by an AI.
  pub is_ai_generated: bool,
}
impl Recipe {
  pub fn new(
    uuid: String,
    user_uuid: String,
    created_at: u32,
    last_updated: u32,
    name: String,
    ingredients: Vec<(String, f32, IngredientUnit)>,
    instructions: Option<String>,
    category: Option<String>,
    image: Option<String>,
    is_ai_generated: u8
  ) -> Self {
    Self {
      uuid,
      user_uuid,
      created_at,
      last_updated,
      name,
      ingredients,
      instructions,
      category,
      image,
      is_ai_generated: is_ai_generated == 1,
    }
  }

  pub async fn serialize(&self, db: &mut SqliteConnection) -> SerializedRecipe {
    let likes: (u32,) = sqlx::query_as("SELECT COUNT(*) FROM recipes_liked WHERE recipe_uuid = $1").bind(&self.uuid).fetch_one(&mut *db).await.unwrap();

    SerializedRecipe {
      uuid: self.uuid.clone(),
      user_uuid: self.user_uuid.clone(),
      created_at: self.created_at,
      last_updated: self.last_updated,
      name: self.name.clone(),
      ingredients: self.ingredients.clone(),
      instructions: self.instructions.clone(),
      category: self.category.clone(),
      image: self.image.clone(),
      likes: likes.0,
      is_ai_generated: self.is_ai_generated,
    }
  }

  pub async fn from_uuid(db: &mut SqliteConnection, uuid: String) -> Option<Self> {
    sqlx
      ::query("SELECT * FROM recipes WHERE uuid = $1")
      .bind(&uuid)
      .fetch_one(&mut *db).await
      .and_then(|row: SqliteRow| {
        Ok(
          Self::new(
            get_from_row(&row, "uuid"),
            get_from_row(&row, "user_uuid"),
            get_from_row(&row, "created_at"),
            get_from_row(&row, "last_updated"),
            get_from_row(&row, "name"),
            from_str(&get_from_row::<String>(&row, "ingredients")).unwrap(),
            get_from_row(&row, "instructions"),
            get_from_row(&row, "category"),
            get_from_row(&row, "image"),
            get_from_row(&row, "is_ai_generated")
          )
        )
      })
      .ok()
  }
}
